version: '3.9'

services:
  nuxt:
    container_name: nuxt
    build: .
    volumes:
      - .:/app:consistent
      - nuxt_node_modules:/app/node_modules
    ports:
      - "80:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=80
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn install && yarn run dev"
volumes:
  nuxt_node_modules:
